---
apiVersion: apps/v1
kind: Deployment

metadata:
  name : himalayan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appforhimalayan
  template:
    metadata:
      labels:
        app: appforhimalayan
    spec:
      containers:
        - name: himalayan1
          image: girish071/private:himalayan
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: resecret
---
apiVersion: v1
kind: Service

metadata:
  name: himalayansvc

spec:
  type: NodePort
  selector:
    app: appforhimalayan
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  
