---
apiVersion: apps/v1
kind: Deployment

metadata:
  name : girish
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appforgirish
  template:
    metadata:
      labels:
        app: appforgirish
    spec:
      containers:
        - name: girishapp
          image: girish071/devops:flight
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service

metadata:
  name: serviceforgirishapp

spec:
  type: NodePort
  selector:
    app: appforgirish
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  
